/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernmentCallerRegistry } from "./GovernmentCallerRegistry";
export * as factories from "./factories";
export { GovernmentCallerRegistry__factory } from "./factories/GovernmentCallerRegistry__factory";
